# Dependabot Configuration
# For full documentation:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Example: NPM Dependencies
  - package-ecosystem: "npm"         # "npm", "pip", "maven", "cargo", etc.
    directory: "/"                   # Root directory (or subfolder) for package manifests
    schedule:
      interval: "weekly"             # Possible values: "daily", "weekly", or "monthly"
      day: "monday"                  # Day of the week for creating PRs
      time: "06:00"                  # UTC time
    # How many open Dependabot PRs to allow at once
    open-pull-requests-limit: 5
    # Automatically rebase PRs if there are merge conflicts
    rebase-strategy: "auto"

    # Commit message & PR naming conventions
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include-scope: true
    pull-request-title: "chore(deps): Update dependencies"

    # Apply these labels to new PRs
    labels:
      - "dependencies"
      - "automated"

    # Optional: auto-assign or auto-request reviews from specified users
    assignees:
      - "LCSOGthb"
    reviewers:
      - "LCSOGthb"

    # Optional: provide a custom rebase schedule (in addition to the standard update schedule).
    # This can help if your project requires frequent merges to stay in sync.
    # rebase-strategy: "auto"

    # Optional: selectively ignore certain dependencies or versions
    # ignore:
    #   - dependency-name: "some-package"
    #     versions: [">=2.0.0, <2.2.0"]
    #   - dependency-name: "another-package"
    #     update-types: ["version-update:semver-minor", "version-update:semver-major"]

  # Example: Additional ecosystem or folder (uncomment & customize if needed)
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "06:00"
  #   open-pull-requests-limit: 3
  #   rebase-strategy: "auto"
  #   commit-message:
  #     prefix: "deps"
  #     include-scope: true
  #   pull-request-title: "chore(ci): Update GitHub Actions"
  #   labels:
  #     - "ci"
  #     - "automated"
  #   assignees:
  #     - "devops-person"

  # Example: Python dependencies
  # - package-ecosystem: "pip"
  #   directory: "/python"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 5
  #   rebase-strategy: "auto"
  #   ...

